name: dist
on: workflow_dispatch
jobs:
  build:
    name: Build Linux binaries -  ${{ matrix.os }} $
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest]
          julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    # Get a patched version of JuliaC
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(url="https://github.com/apozharski/JuliaC.jl.git"); Pkg.Apps.add(url="https://github.com/apozharski/JuliaC.jl.git")'
    - name: add JuliaC to path
      run: echo "$HOME/.julia/bin" >> "$GITHUB_PATH"
    - name:
      run: mkdir build && cd build && cmake .. && make
    - uses: actions/upload-artifact@v4
      with:
        name: libMad-${{ matrix.os }}
        path: |
          build/lib
          build/share
          build/include
          build/basic_problem