name: dist
on: workflow_dispatch
jobs:
  build:
    name: Build Linux binaries -  ${{ matrix.os }} $
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest]
          julia-version: ['1']
          julia-arch: [x64]
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add("JuliaC"); Pkg.Apps.add("JuliaC")'
    - name: add JuliaC to path
      run: echo "$HOME/.julia/bin" >> "$GITHUB_PATH"
    - name: dev libmad
      run: julia -e 'using Pkg; Pkg.develop(path=".");Pkg.status()'
    - name: 
      run: mkdir build && cd build && cmake .. && make