name: dist
on: workflow_dispatch
jobs:
  build_linux:
    name: Build binaries - ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    # Get a patched version of JuliaC
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(url="https://github.com/apozharski/JuliaC.jl.git"); Pkg.Apps.add(url="https://github.com/apozharski/JuliaC.jl.git")'
    - name: add JuliaC to path
      run: echo "$HOME/.julia/bin" >> "$GITHUB_PATH"
    - name: build libMad
      run: mkdir build && cd build && mkdir install && cmake .. -DCMAKE_INSTALL_PREFIX="install" && cmake --build . --target install --config Release
    - name: tar output
      run: cd build/install && tar -czf ../../libMad-ubuntu-latest.tar.gz *
    - uses: actions/upload-artifact@v4
      with:
        name: libMad-ubuntu-latest
        path: libMad-ubuntu-latest.tar.gz
  build_windows:
    name: Build binaries - windows-latest
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - name: Configure to use mingw
      run: |
        echo "CC=gcc" >> $GITHUB_ENV
        echo "CXX=g++" >> $GITHUB_ENV
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(url="https://github.com/apozharski/JuliaC.jl.git"); Pkg.Apps.add(url="https://github.com/apozharski/JuliaC.jl.git")'
    - name: add JuliaC to path
      run: echo "PATH=$HOME\.julia\bin;$env:PATH" >> $env:GITHUB_ENV
      shell: pwsh
    - name: build libMad
      run: mkdir build && cd build && mkdir install && cmake .. -DCMAKE_INSTALL_PREFIX="install" && cmake --build . --target INSTALL --config Release
    - name: zip output
      run: |
        cd build\install && tar.exe -czf ..\..\libMad-windows-latest.tar.gz *
    - uses: actions/upload-artifact@v4
      with:
        name: libMad-windows-latest
        path: libMad-windows-latest.tar.gz
    # - name: debug print
    #   if: always()
    #   run: Get-ChildItem -Recurse "."