name: dist
on: workflow_dispatch
jobs:
  build_linux:
    name: Build binaries - ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    # Get a patched version of JuliaC
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(url="https://github.com/apozharski/JuliaC.jl.git"); Pkg.Apps.add(url="https://github.com/apozharski/JuliaC.jl.git")'
    - name: add JuliaC to path
      run: echo "$HOME/.julia/bin" >> "$GITHUB_PATH"
    - name: build libMad
      run: mkdir build && cd build && cmake .. && make
    - name: tar output
      run: tar -czf libMad-ubuntu-latest.tar.gz build/lib/ build/share/ build/include/ build/basic_problem
    - uses: actions/upload-artifact@v4
      with:
        name: libMad-ubuntu-latest
        path: libMad-ubuntu-latest.tar.gz
  build_windows:
    name: Build binaries - windows-latest
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(url="https://github.com/apozharski/JuliaC.jl.git"); Pkg.Apps.add(url="https://github.com/apozharski/JuliaC.jl.git")'
    - name: add JuliaC to path
      run: "$env:HOMEPATH/.julia/bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append
    - name: build libMad
      run: mkdir build && cd build && cmake .. && make