name: publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"
jobs:
  build_linux:
    name: Build binaries - ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    # Get a patched version of JuliaC
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(url="https://github.com/apozharski/JuliaC.jl.git"); Pkg.Apps.add(url="https://github.com/apozharski/JuliaC.jl.git")'
    - name: add JuliaC to path
      run: echo "$HOME/.julia/bin" >> "$GITHUB_PATH"
    - name: build libMad
      run: mkdir build && cd build && mkdir install && cmake .. -DCMAKE_INSTALL_PREFIX="install" && cmake --build . --target install --config Release
    - name: tar output
      run: cd build/install && tar -czf ../../libMad-ubuntu-x86_64-${{ github.ref_name }}.tar.gz *
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libMad-ubuntu-x86_64-${{ github.ref_name }}.tar.gz
        asset_name: libMad-ubuntu-x86_64-${{ github.ref_name }}.tar.gz
        tag: ${{ github.ref }}
        body: "Release ${{ github.ref_name }}"
  build_windows:
    name: Build binaries - windows-latest
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(url="https://github.com/apozharski/JuliaC.jl.git"); Pkg.Apps.add(url="https://github.com/apozharski/JuliaC.jl.git")'
    - name: add JuliaC to path
      run: echo "PATH=$HOME\.julia\bin;$env:PATH" >> $env:GITHUB_ENV
      shell: pwsh
    - name: build libMad
      run: mkdir build && cd build && mkdir install && cmake .. -DCMAKE_INSTALL_PREFIX="install" && cmake --build . --target INSTALL --config Release
    - name: tar output
      run: |
        cd build\install && tar.exe -czf ..\..\libMad-windows-x86_64-${{ github.ref_name }}.tar.gz *
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libMad-windows-x86_64-${{ github.ref_name }}.tar.gz
        asset_name: libMad-windows-x86_64-${{ github.ref_name }}.tar.gz
        tag: ${{ github.ref }}
        body: "Release ${{ github.ref_name }}"
  build_apple:
    name: Build binaries - mac-latest
    runs-on: mac-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(url="https://github.com/apozharski/JuliaC.jl.git"); Pkg.Apps.add(url="https://github.com/apozharski/JuliaC.jl.git")'
    - name: add JuliaC to path
      run: echo "PATH=$HOME\.julia\bin;$env:PATH" >> $env:GITHUB_ENV
      shell: pwsh
    - name: build libMad
      run: mkdir build && cd build && mkdir install && cmake .. -DCMAKE_INSTALL_PREFIX="install" && cmake --build . --target INSTALL --config Release
    -  name: tar output
      run: |
        cd build\install && tar.exe -czf ..\..\libMad-apple-aarch64-${{ github.ref_name }}.tar.gz *
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libMad-apple-aarch64-${{ github.ref_name }}.tar.gz
        asset_name: libMad-apple-aarch64-${{ github.ref_name }}.tar.gz
        tag: ${{ github.ref }}
        body: "Release ${{ github.ref_name }}"
